services:
  backend:
    build: backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_HOST_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_ACCESS_TOKEN: ${JWT_ACCESS_TOKEN}
      JWT_ACCESS_TOKEN_EXPIRES: ${JWT_ACCESS_TOKEN_EXPIRES}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_TOKEN}
      JWT_REFRESH_TOKEN_EXPIRES: ${JWT_REFRESH_TOKEN_EXPIRES}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_PASS: ${GMAIL_PASS}
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./frontend/config:/etc/nginx/conf.d:ro
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  db-data:
